# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "users",
  "activation_tokens",
  "images",
  "campaigns",
  "tokens"
]

const attributes = [
  Attr(name: "uuid", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "fullname", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "email", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "pw_hash", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "is_advertiser", tabIndex: 0, typ: dbInt, key: 0),
  Attr(name: "activated", tabIndex: 0, typ: dbInt, key: 0),
  Attr(name: "created_at", tabIndex: 0, typ: dbTimestamp, key: 0),
  Attr(name: "deleted_at", tabIndex: 0, typ: dbInt, key: 0),
  Attr(name: "token", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "already_used", tabIndex: 1, typ: dbInt, key: 0),
  Attr(name: "user_id", tabIndex: 1, typ: dbVarchar, key: -1),
  Attr(name: "uuid", tabIndex: 2, typ: dbVarchar, key: 0),
  Attr(name: "image", tabIndex: 2, typ: dbBlob, key: 0),
  Attr(name: "uuid", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "creator", tabIndex: 3, typ: dbVarchar, key: -1),
  Attr(name: "title", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "box_image_id", tabIndex: 3, typ: dbVarchar, key: -12),
  Attr(name: "plaintext", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "target_url", tabIndex: 3, typ: dbVarchar, key: 0),
  Attr(name: "created_at", tabIndex: 3, typ: dbTimestamp, key: 0),
  Attr(name: "updated_at", tabIndex: 3, typ: dbTimestamp, key: 0),
  Attr(name: "deleted_at", tabIndex: 3, typ: dbTimestamp, key: 0),
  Attr(name: "uuid", tabIndex: 4, typ: dbVarchar, key: 0),
  Attr(name: "creator", tabIndex: 4, typ: dbVarchar, key: -1),
  Attr(name: "token", tabIndex: 4, typ: dbVarchar, key: 0),
  Attr(name: "created_at", tabIndex: 4, typ: dbTimestamp, key: 0),
  Attr(name: "deleted_at", tabIndex: 4, typ: dbTimestamp, key: 0)
]
